### ISSUE TITLE
Exclude db doesn't work ?

### ISSUE THREAD

**Issue by nenominal** [dataegret/pgcompacttable#23]
> pgcompacttable -a -D test -U postgres
> 
> Unknown option: D
> Usage:
>     pgcompacttable [OPTION...]
> 
>     General options:
>         [-?mV] [(-q | -v LEVEL)]
> 
>     Connection options:
>         [-h HOST] [-p PORT] [-U USER] [-W PASSWD] [-P PATH]
> 
>     Targeting options:
>         (-a | -d DBNAME...) [-n SCHEMA...] [-t TABLE...] [-D DBNAME...] [-N
>         SCHEMA...] [-T TABLE...]
> 

> pgcompacttable -a --exclude-dbname test -U postgres
> Unknown option: exclude-dbname
> Usage:
>     pgcompacttable [OPTION...]
> 
>     General options:
>         [-?mV] [(-q | -v LEVEL)]
> 
>     Connection options:
>         [-h HOST] [-p PORT] [-U USER] [-W PASSWD] [-P PATH]
> 
>     Targeting options:
>         (-a | -d DBNAME...) [-n SCHEMA...] [-t TABLE...] [-D DBNAME...] [-N
>         SCHEMA...] [-T TABLE...]

**Comment by Melkij** [comment]
Hi
hmm... Interesting. AFAIK we never had --exclude-dbname option. I will remove this from help.

**Comment by nenominal** [comment]
Can I pass to --dbname multiple db or do I have to run it individually for each db?

**Comment by Melkij** [comment]
Its possible only by run individually for each db. --dbname accepts only one db name
