### ISSUE TITLE
Need a documented way to connect via unix socket

### ISSUE THREAD

**Issue by pyhalov** [dataegret/pgcompacttable#29]
I haven't found any way to use peer auth with this script without modifying it to omit 'host=' parameter.

**Comment by Melkij** [comment]
Hello
You can use standard libpq behavior and specify unix socket directory as hostname, `-h /tmp` (postgresql from scratch) or `-h /var/run/postgresql` (debian/ubuntu packages). (check your `unix_socket_directories` postgresql setting)

I will keep this issue open. Possible I need change default connect method to unixsock, like psql and other libpq software.

**Comment by Melkij** [comment]
Hi
I changed default host  and port to use libpq defaults. So by default tool will use unixsock
