### ISSUE TITLE
option "--routine-vacuum"

### ISSUE THREAD

**Issue by glushakov** [dataegret/pgcompacttable#39]
Hi.
Can you explain more detailed option:
 --routine-vacuum
        Turn on the routine vacuum. By default all the vacuums are off.

I did not find any ALTER about disabling VACUUM on tables in code
Thanks

**Comment by Melkij** [comment]
Hello
It's not about disabling vacuum in any way. With this option we perform _additional_ vacuum while moving rows in a table.
By default for each table:
- vacuum
- calculate bloat
- move tuples from end table to beginning
- vacuum

With --routine-vacuum we call additional vacuum few times while moving the tuples.

Can be used if the auto vacuum is too slow, for example. Or to return space to OS earlier from the tail of the table.

**Comment by glushakov** [comment]
Ok, thanks for explanation
