### ISSUE TITLE
recreating constraints missing deferrable

### ISSUE THREAD

**Issue by opb1978** [dataegret/pgcompacttable#4]
We have noticed that the script is not respecting all settings of original constraints. 

In our case we use DEFERRABLE with a constraint after using the script deferrable was gone.

> ALTER TABLE ONLY lot
>  -ADD CONSTRAINT ukey_lot UNIQUE (street_id, city_id, zip_id, housenumber, block, staircase) DEFERRABLE;
> +ADD CONSTRAINT ukey_lot UNIQUE (street_id, city_id, zip_id, housenumber, block, staircase);

In our case we actually did not need deferrable but the script should respect all original settings

**Comment by Melkij** [comment]
Hi
I fixed this error in #10 and today PR was merged to master.
