### ISSUE TITLE
Missing argument in sprintf at ./pgcompacttable line 180.

### ISSUE THREAD

**Issue by webervin** [dataegret/pgcompacttable#5]
```
[Thu Nov 26 08:12:16 2015] (dbname:tablename) Skipping index indexname:
[Thu Nov 26 08:12:16 2015] (dbname:tablename) SQL Error: ERROR:  relation "pgcompact_index_25734" already exists
Missing argument in sprintf at ./pgcompacttable line 180.
```

where 25734 is pid of ./pgcompacttable, 
(used current master version,  122a6d2 as: `./pgcompacttable --host/var/run/postgresql/ --dbname stagingdbname --verbose`)
perl:

```
 /usr/bin/perl --version

This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
(with 41 registered patches, see perl -V for more detail)

Copyright 1987-2013, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

on ubuntu: 

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
```

trying first time against db cluster:

```
psql -c 'show server_version';
 server_version
----------------
 9.3.10
(1 row)
```

**Comment by ghost** [comment]
Hi,

Try remove the index pgcompact_index_25734 and start the process again.

**Comment by webervin** [comment]
as errors feels to be only related to outputing info, i will wait for "clean exit" first (around hour probably), will try dropping index before next attempt though.

**Comment by webervin** [comment]
| Try remove the index pgcompact_index_25734 and start the process again.
worked. thanks. 

any insight how this could have happened,and can any harm come out of this?

**Comment by ghost** [comment]
This problem is related that before running your process fails and the index remained. 
Next, you try to re-start the process , the process generated an error (SQL Error: ERROR:  relation ....) on the existence of an index.

**Comment by webervin** [comment]
thanks, it did indeed fail on first try, due to attempt connecting to localhost instead of socket by default.
Closing.

PS great script.
